name: Security Analysis

on:
  workflow_dispatch:

jobs:
  bandit-scan:
    name: Bandit Python Linting
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Perform Bandit Analysis
        uses: PyCQA/bandit-action@v1
        with:
          python-version: "3.14"
          severity: "medium"
          confidence: "medium"
          exclude: "tests,venv,env,build,dist,.git"
          targets: "."

      - name: Install Bandit
        run: pip install bandit

      - name: Generate SARIF
        run: bandit -r . --format sarif --output bandit-results.sarif --exclude tests,venv,env,build,dist,.git

      - name: Upload Bandit SARIF
        uses: actions/upload-artifact@v7
        with:
          name: Bandit SARIF
          path: bandit-results.sarif

  dependency-check:
    name: OWASP Dependency-Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@v8.0.0
        with:
          version: "latest"

      - name: Generate requirements file
        run: uv export --format requirements-txt --output-file requirements.txt

      - name: Depcheck
        uses: dependency-check/Dependency-Check_Action@main
        id: Depcheck
        with:
          project: 'python-project'
          path: 'requirements.txt'
          format: 'HTML'
          out: 'reports'
          args: >
            --failOnCVSS 7
            --enableRetired

      - name: Upload Test results
        uses: actions/upload-artifact@v7
        with:
           name: Depcheck report
           path: ${{github.workspace}}/reports

  secret-scanning:
    name: Secret Scanning
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Secret Scanning
        uses: trufflesecurity/trufflehog@main
        with:
          extra_args: --results=verified,unknown
